# Copyright (c) 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:
  - import: false
    name: pigweed
    path: third_party/pigweed
    remote: pigweed
    revision: 5477cb202c57ede4bf9981f4ab067abec1bdb6cf
  - import: true
    name: zephyr
    path: third_party/pigweed/environment/packages/zephyr
    remote: zephyr
    revision: f9778472105d756fff7d1e5b54353421d356ed43
  remotes:
  - name: pigweed
    url-base: git@github.com:google/pigweed.git
  - name: zephyr
    url-base: https://pigweed.googlesource.com/third_party/github/zephyrproject-rtos/zephyr
